before_install:
- openssl aes-256-cbc -K $encrypted_b2df56cc9e48_key -iv $encrypted_b2df56cc9e48_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
language: ruby
cache: bundler
rvm:
- 2.0.0-p648
script: JEKYLL_ENV=production bundle exec jekyll build
notifications:
  email:
    recipients:
      - $NOTIFY_EMAIL
    on_success: never # default: always
    on_failure: always # default: always
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- cp -v .travis/ssh-config ~/.ssh/config
- cd /home/travis/build/dylanon/site/_site
- scp -r . $DEPLOY_STAGING
- cd ..
- git remote -v add deploy $DEPLOY_REPO
- git fetch --unshallow
- git push deploy master
sudo: false