before_install:
- openssl aes-256-cbc -K $encrypted_b2df56cc9e48_key -iv $encrypted_b2df56cc9e48_iv -in .travis/deploy_key.enc -out .travis/deploy_key -d
language: ruby
rvm:
- 2.0.0-p648
script: JEKYLL_ENV=production bundle exec jekyll build
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/deploy_key
- ssh-add .travis/deploy_key
- git remote add deploy $DEPLOY_REPO
- yes | git push deploy master
sudo: false